//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Presentation.App_Start {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemBR_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemBR_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemBRPresentation.App_Start.SystemBR_Resource", typeof(SystemBR_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail invalido.
        /// </summary>
        internal static string M0001 {
            get {
                return ResourceManager.GetString("M0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login não cadastrado.
        /// </summary>
        internal static string M0002 {
            get {
                return ResourceManager.GetString("M0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuario esta inativo.
        /// </summary>
        internal static string M0003 {
            get {
                return ResourceManager.GetString("M0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuario esta bloqueado. Entre em contato com o administrador do sistema para executar o desbloqueio.
        /// </summary>
        internal static string M0004 {
            get {
                return ResourceManager.GetString("M0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuario ja efetuou um login com a senha provisoria. Favor gerar outra senha.
        /// </summary>
        internal static string M0005 {
            get {
                return ResourceManager.GetString("M0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de falhas de login superior ao limite diario de falhas.
        /// </summary>
        internal static string M0006 {
            get {
                return ResourceManager.GetString("M0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciais invalidas.
        /// </summary>
        internal static string M0007 {
            get {
                return ResourceManager.GetString("M0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha nao pode ser igual a anterior.
        /// </summary>
        internal static string M0008 {
            get {
                return ResourceManager.GetString("M0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha nao foi confirmada corretamente.
        /// </summary>
        internal static string M0009 {
            get {
                return ResourceManager.GetString("M0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua pesquisa não retornou nenhum resultado - Tente outras opções de pesquisa.
        /// </summary>
        internal static string M0010 {
            get {
                return ResourceManager.GetString("M0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo do banco ja existente.
        /// </summary>
        internal static string M0011 {
            get {
                return ResourceManager.GetString("M0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este banco ja contem contas vinculadas. Impossivel ser excluido..
        /// </summary>
        internal static string M0012 {
            get {
                return ResourceManager.GetString("M0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta bancaria ja cadastrada.
        /// </summary>
        internal static string M0013 {
            get {
                return ResourceManager.GetString("M0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir esta conta. Existem lancamentos de CONTAS A PAGAR vinculados a ela.
        /// </summary>
        internal static string M0014 {
            get {
                return ResourceManager.GetString("M0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir esta conta. Existem lancamentos de CONTAS A RECEBER vinculados a ela.
        /// </summary>
        internal static string M0015 {
            get {
                return ResourceManager.GetString("M0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filial ja cadastrada.
        /// </summary>
        internal static string M0016 {
            get {
                return ResourceManager.GetString("M0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir essa filial. Existem registros vinculados a ela.
        /// </summary>
        internal static string M0017 {
            get {
                return ResourceManager.GetString("M0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente ja cadastrado.
        /// </summary>
        internal static string M0018 {
            get {
                return ResourceManager.GetString("M0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir esse cliente. Existem registros vinculados a ele..
        /// </summary>
        internal static string M0019 {
            get {
                return ResourceManager.GetString("M0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor ja cadastrado.
        /// </summary>
        internal static string M0020 {
            get {
                return ResourceManager.GetString("M0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir esse fornecedor. Existem registros vinculados a ele..
        /// </summary>
        internal static string M0021 {
            get {
                return ResourceManager.GetString("M0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto ja cadastrado.
        /// </summary>
        internal static string M0022 {
            get {
                return ResourceManager.GetString("M0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir esse produto. Existem registros vinculados a ele..
        /// </summary>
        internal static string M0023 {
            get {
                return ResourceManager.GetString("M0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materia prima ja cadastrada.
        /// </summary>
        internal static string M0024 {
            get {
                return ResourceManager.GetString("M0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir essa materia prima. Existem registros vinculados a ele..
        /// </summary>
        internal static string M0025 {
            get {
                return ResourceManager.GetString("M0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servico ja cadastrado.
        /// </summary>
        internal static string M0026 {
            get {
                return ResourceManager.GetString("M0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir esse serviço. Existem registros vinculados a ele..
        /// </summary>
        internal static string M0027 {
            get {
                return ResourceManager.GetString("M0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportadora ja cadastrada.
        /// </summary>
        internal static string M0028 {
            get {
                return ResourceManager.GetString("M0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir essa transportadora, Existem registros vinculados a ela..
        /// </summary>
        internal static string M0029 {
            get {
                return ResourceManager.GetString("M0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item de patrimonio ja cadastrado.
        /// </summary>
        internal static string M0030 {
            get {
                return ResourceManager.GetString("M0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipamento ja cadastrado.
        /// </summary>
        internal static string M0031 {
            get {
                return ResourceManager.GetString("M0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo ja cadastrado.
        /// </summary>
        internal static string M0032 {
            get {
                return ResourceManager.GetString("M0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir esse cargo, Existem registros vinculados a ele..
        /// </summary>
        internal static string M0033 {
            get {
                return ResourceManager.GetString("M0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor/Tipo de comissão já cadastrado.
        /// </summary>
        internal static string M0034 {
            get {
                return ResourceManager.GetString("M0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir esse tipo/valor de comissão. Existem registros vinculados a ele..
        /// </summary>
        internal static string M0035 {
            get {
                return ResourceManager.GetString("M0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato invalido para foto, Deve ser JPG, GIF ou PNG.
        /// </summary>
        internal static string M0036 {
            get {
                return ResourceManager.GetString("M0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato ja cadastrado.
        /// </summary>
        internal static string M0037 {
            get {
                return ResourceManager.GetString("M0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir esse contrato. Existem registros vinculados a ele..
        /// </summary>
        internal static string M0038 {
            get {
                return ResourceManager.GetString("M0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitacao de aprovacao enviada.
        /// </summary>
        internal static string M0039 {
            get {
                return ResourceManager.GetString("M0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato cancelado.
        /// </summary>
        internal static string M0040 {
            get {
                return ResourceManager.GetString("M0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do arquivo anexado não pode ser maior que 100 caracteres.
        /// </summary>
        internal static string M0041 {
            get {
                return ResourceManager.GetString("M0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato nao aprovado.
        /// </summary>
        internal static string M0042 {
            get {
                return ResourceManager.GetString("M0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O contrato nao esta na fase OPERAÇÃO.
        /// </summary>
        internal static string M0043 {
            get {
                return ResourceManager.GetString("M0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail enviado com sucesso.
        /// </summary>
        internal static string M0044 {
            get {
                return ResourceManager.GetString("M0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir esse item de tabela auxiliar. existem registros vinculados a ele..
        /// </summary>
        internal static string M0045 {
            get {
                return ResourceManager.GetString("M0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template ja cadastrado.
        /// </summary>
        internal static string M0046 {
            get {
                return ResourceManager.GetString("M0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir esse lancamento de conta a receber. existem registros vinculados a ele..
        /// </summary>
        internal static string M0047 {
            get {
                return ResourceManager.GetString("M0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data nao pode ser maior do que a data corrente.
        /// </summary>
        internal static string M0048 {
            get {
                return ResourceManager.GetString("M0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A soma das parcelas nao bate com o valor total informado.
        /// </summary>
        internal static string M0049 {
            get {
                return ResourceManager.GetString("M0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um lancamento parcelado nao pode ter pagamento parcial.
        /// </summary>
        internal static string M0050 {
            get {
                return ResourceManager.GetString("M0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do pagamento parcial nao pode ser maior que o valor do lancamento.
        /// </summary>
        internal static string M0051 {
            get {
                return ResourceManager.GetString("M0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor parcial igual ao valor do lancamento. Va para liquidacao de lancamento ao inves de pagamento parcial.
        /// </summary>
        internal static string M0052 {
            get {
                return ResourceManager.GetString("M0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de inicio nao pode ser menor que a data corrente.
        /// </summary>
        internal static string M0053 {
            get {
                return ResourceManager.GetString("M0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O numero de parcelas nao pode ser menor do que 2.
        /// </summary>
        internal static string M0054 {
            get {
                return ResourceManager.GetString("M0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel liquidar direto um lançamento parcelado. As parcelas devem ser liquidadas uma a uma..
        /// </summary>
        internal static string M0055 {
            get {
                return ResourceManager.GetString("M0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel fazer pagamento parcial de um lancamento parcelado.
        /// </summary>
        internal static string M0056 {
            get {
                return ResourceManager.GetString("M0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel parcelar um lancamento com pagamento parcial.
        /// </summary>
        internal static string M0057 {
            get {
                return ResourceManager.GetString("M0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa ja cadastrada.
        /// </summary>
        internal static string M0058 {
            get {
                return ResourceManager.GetString("M0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de encerramento da tarefa menor que a data de inicio.
        /// </summary>
        internal static string M0059 {
            get {
                return ResourceManager.GetString("M0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de encerramento da tarefa maior que a data corrente.
        /// </summary>
        internal static string M0060 {
            get {
                return ResourceManager.GetString("M0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel compartilhar tarefa com o proprio usuario.
        /// </summary>
        internal static string M0061 {
            get {
                return ResourceManager.GetString("M0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido de compra ja cadastrado.
        /// </summary>
        internal static string M0062 {
            get {
                return ResourceManager.GetString("M0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir este pedido pois existem registros vinculados a ele.
        /// </summary>
        internal static string M0063 {
            get {
                return ResourceManager.GetString("M0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item de pedido incompleto.
        /// </summary>
        internal static string M0064 {
            get {
                return ResourceManager.GetString("M0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item de pedido sem valor.
        /// </summary>
        internal static string M0065 {
            get {
                return ResourceManager.GetString("M0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item de pedido sem quantidade.
        /// </summary>
        internal static string M0066 {
            get {
                return ResourceManager.GetString("M0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item de pedido sem data de cotação.
        /// </summary>
        internal static string M0067 {
            get {
                return ResourceManager.GetString("M0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cancelamento requer que a justificativa seja preenchida.
        /// </summary>
        internal static string M0068 {
            get {
                return ResourceManager.GetString("M0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido de venda ja cadastrado.
        /// </summary>
        internal static string M0070 {
            get {
                return ResourceManager.GetString("M0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atendimento ja cadastrado.
        /// </summary>
        internal static string M0071 {
            get {
                return ResourceManager.GetString("M0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir este atendimento pois existem registros vinculados a ele.
        /// </summary>
        internal static string M0072 {
            get {
                return ResourceManager.GetString("M0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha não pode ficar em branco.
        /// </summary>
        internal static string M0073 {
            get {
                return ResourceManager.GetString("M0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova senha não pode ser em branco.
        /// </summary>
        internal static string M0074 {
            get {
                return ResourceManager.GetString("M0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação da senha não pode ser em branco.
        /// </summary>
        internal static string M0075 {
            get {
                return ResourceManager.GetString("M0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum arquivo selecionado.
        /// </summary>
        internal static string M0076 {
            get {
                return ResourceManager.GetString("M0076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionario ja cadastrado.
        /// </summary>
        internal static string M0077 {
            get {
                return ResourceManager.GetString("M0077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir este funcionario pois existem registros vinculados a ele.
        /// </summary>
        internal static string M0078 {
            get {
                return ResourceManager.GetString("M0078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel excluir este lancamento. Ele esta relacionado com outros registros.
        /// </summary>
        internal static string M0083 {
            get {
                return ResourceManager.GetString("M0083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de inicio de parcelamento menor que a data corrente.
        /// </summary>
        internal static string M0084 {
            get {
                return ResourceManager.GetString("M0084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de parcelas menor do que 2.
        /// </summary>
        internal static string M0085 {
            get {
                return ResourceManager.GetString("M0085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel liquidar um lancamento parcelado. As parcelas devem ser liquidadas individualmente.
        /// </summary>
        internal static string M0086 {
            get {
                return ResourceManager.GetString("M0086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de liquidacao maior que a data corrente.
        /// </summary>
        internal static string M0087 {
            get {
                return ResourceManager.GetString("M0087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soma dos itens diferente do valor total.
        /// </summary>
        internal static string M0088 {
            get {
                return ResourceManager.GetString("M0088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel pagar parcial um lancamento parcelado.
        /// </summary>
        internal static string M0089 {
            get {
                return ResourceManager.GetString("M0089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor parcial maior que o valor total.
        /// </summary>
        internal static string M0090 {
            get {
                return ResourceManager.GetString("M0090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor parcial igual ao valor total.
        /// </summary>
        internal static string M0091 {
            get {
                return ResourceManager.GetString("M0091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossivel parcelar lancamento com pagamento parcial.
        /// </summary>
        internal static string M0092 {
            get {
                return ResourceManager.GetString("M0092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você tem notificações não lidas até esta data.
        /// </summary>
        internal static string M0093 {
            get {
                return ResourceManager.GetString("M0093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você tem tarefas pendentes até esta data.
        /// </summary>
        internal static string M0094 {
            get {
                return ResourceManager.GetString("M0094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento recorrente não pode ser parcelado.
        /// </summary>
        internal static string M0095 {
            get {
                return ResourceManager.GetString("M0095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inicial das ocorrências não definida.
        /// </summary>
        internal static string M0096 {
            get {
                return ResourceManager.GetString("M0096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soma dos percentuais de rateio maior do que 100.
        /// </summary>
        internal static string M0097 {
            get {
                return ResourceManager.GetString("M0097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse produto é COMPOSTO e não tem Ficha Técnica especificada..
        /// </summary>
        internal static string M0098 {
            get {
                return ResourceManager.GetString("M0098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela de preço já cadastrada para este produto/filial.
        /// </summary>
        internal static string M0099 {
            get {
                return ResourceManager.GetString("M0099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido de compra já cadastrado.
        /// </summary>
        internal static string M0100 {
            get {
                return ResourceManager.GetString("M0100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossível excluir esse pedido. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0101 {
            get {
                return ResourceManager.GetString("M0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum item incluído no pedido ou existem itens sem dados de cotação.
        /// </summary>
        internal static string M0102 {
            get {
                return ResourceManager.GetString("M0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem itens sem preço no pedido.
        /// </summary>
        internal static string M0103 {
            get {
                return ResourceManager.GetString("M0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem itens sem quantidade no pedido.
        /// </summary>
        internal static string M0104 {
            get {
                return ResourceManager.GetString("M0104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem itens sem data de cotação no pedido.
        /// </summary>
        internal static string M0105 {
            get {
                return ResourceManager.GetString("M0105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A justificativa de cancelamento e obrigatória.
        /// </summary>
        internal static string M0106 {
            get {
                return ResourceManager.GetString("M0106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de início do parcelamento deve ser especificada.
        /// </summary>
        internal static string M0107 {
            get {
                return ResourceManager.GetString("M0107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela de preço já cadastrada para este insumo/filial.
        /// </summary>
        internal static string M0108 {
            get {
                return ResourceManager.GetString("M0108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login não pode ficar em branco.
        /// </summary>
        internal static string M0109 {
            get {
                return ResourceManager.GetString("M0109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto já cadastrado.
        /// </summary>
        internal static string M0110 {
            get {
                return ResourceManager.GetString("M0110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insumo já cadastrado.
        /// </summary>
        internal static string M0111 {
            get {
                return ResourceManager.GetString("M0111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço já cadastrado.
        /// </summary>
        internal static string M0112 {
            get {
                return ResourceManager.GetString("M0112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportadora já cadastrada.
        /// </summary>
        internal static string M0113 {
            get {
                return ResourceManager.GetString("M0113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especificar Usuário ou Departamento.
        /// </summary>
        internal static string M0114 {
            get {
                return ResourceManager.GetString("M0114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionalidade restrita a administradores.
        /// </summary>
        internal static string M0115 {
            get {
                return ResourceManager.GetString("M0115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo já cadastrado.
        /// </summary>
        internal static string M0116 {
            get {
                return ResourceManager.GetString("M0116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subgrupo já cadastrado.
        /// </summary>
        internal static string M0117 {
            get {
                return ResourceManager.GetString("M0117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossível excluir. existem registros vinculados a ele.
        /// </summary>
        internal static string M0118 {
            get {
                return ResourceManager.GetString("M0118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de pagamento não informada.
        /// </summary>
        internal static string M0119 {
            get {
                return ResourceManager.GetString("M0119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há nenhum registro com data de vencimento para a data atual.
        /// </summary>
        internal static string M0120 {
            get {
                return ResourceManager.GetString("M0120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem de Serviço já cadastrada.
        /// </summary>
        internal static string M0121 {
            get {
                return ResourceManager.GetString("M0121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não possui celular cadastrado.
        /// </summary>
        internal static string M0122 {
            get {
                return ResourceManager.GetString("M0122", resourceCulture);
            }
        }
    }
}
