//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITORIA
    {
        public int LOG_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public System.DateTime LOD_DT_LOG { get; set; }
        public string LOG_NM_OPERACAO { get; set; }
        public byte[] LOG_TX_REGISTRO { get; set; }
        public byte[] LOG_TX_REGISTRO_ANTES { get; set; }
    
        public virtual USUARIO_SUGESTAO USUARIO_SUGESTAO { get; set; }
    }
}
