//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_APOLICE
    {
        public int CLAP_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public int PARC_CD_ID { get; set; }
        public string CLAP_NR_APOLICE { get; set; }
        public System.DateTime CLAP_DT_INICIO_VIGENCIA { get; set; }
        public System.DateTime CLAP_DT_FINAL_VIGENCIA { get; set; }
        public int CLAP_IN_ATIVO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PARCEIRO PARCEIRO { get; set; }
    }
}
