//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_MARKETING_ATIVO
    {
        public int CLMA_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public int PERI_CD_ID { get; set; }
        public int TEMP_CD_ID { get; set; }
        public int CLMA_IN_TIPO_ACAO { get; set; }
        public System.DateTime CLMA_DT_INICIO { get; set; }
        public System.DateTime CLMA_DT_VALIDADE { get; set; }
        public int CLMA_IN_ACAO { get; set; }
        public Nullable<int> CLMA_IN_TEMPO_AVISO { get; set; }
        public System.DateTime CLMA_DT_EXECUTADO { get; set; }
        public int CLMA_IN_ATIVO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PERIODICIDADE PERIODICIDADE { get; set; }
        public virtual TEMPLATE_MENSAGEM TEMPLATE_MENSAGEM { get; set; }
    }
}
