//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_ENDERECO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE_ENDERECO()
        {
            this.ORDEM_SERVICO = new HashSet<ORDEM_SERVICO>();
        }
    
        public int CLEN_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public int TIRE_CD_ID { get; set; }
        public string CLEN_NM_ENDERECO { get; set; }
        public string CLEN_NR_NUMERO { get; set; }
        public string CLEN_NM_COMPLEMENTO { get; set; }
        public string CLEN_NM_BAIRRO { get; set; }
        public string CLEN_NM_CIDADE { get; set; }
        public string CLEN_NR_CEP { get; set; }
        public int UF_CD_ID { get; set; }
        public byte[] CLEN_TX_REFERENCIA_LOCAL { get; set; }
        public int CLEN_IN_ASSISNTENCIA_TECNICA { get; set; }
        public int CLEN_IN_ATIVO { get; set; }
        public string CLEN_TX_REFERENCIA_LOCAL_TEXT { get; set; }
        public string CLEN_NM_EXIBE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual UF UF { get; set; }
        public virtual TIPO_RESIDENCIA TIPO_RESIDENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEM_SERVICO> ORDEM_SERVICO { get; set; }
    }
}
