//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.CLIENTE_ANEXO = new HashSet<CLIENTE_ANEXO>();
            this.CLIENTE_APOLICE = new HashSet<CLIENTE_APOLICE>();
            this.CLIENTE_CONTATO = new HashSet<CLIENTE_CONTATO>();
            this.CLIENTE_ENDERECO = new HashSet<CLIENTE_ENDERECO>();
            this.CLIENTE_HISTORICO = new HashSet<CLIENTE_HISTORICO>();
            this.CLIENTE_MARKETING_ATIVO = new HashSet<CLIENTE_MARKETING_ATIVO>();
            this.CLIENTE_RESPOSTA = new HashSet<CLIENTE_RESPOSTA>();
            this.CONTRATO = new HashSet<CONTRATO>();
            this.ORDEM_SERVICO = new HashSet<ORDEM_SERVICO>();
            this.PESQUISA_RESPOSTA = new HashSet<PESQUISA_RESPOSTA>();
            this.TICKET_ATENDIMENTO = new HashSet<TICKET_ATENDIMENTO>();
        }
    
        public int CLIE_CD_ID { get; set; }
        public int TICL_CD_ID { get; set; }
        public int ORCL_CD_ID { get; set; }
        public int CLIE_IN_TIPO_PESSOA { get; set; }
        public string CLIE_NM_NOME { get; set; }
        public string CLIE_NM_RAZAO_SOCIAL { get; set; }
        public string CLIE_NR_CPF { get; set; }
        public string CLIE_NR_CNPJ { get; set; }
        public System.DateTime CLIE_DT_CADASTRO { get; set; }
        public int CLIE_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_ANEXO> CLIENTE_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_APOLICE> CLIENTE_APOLICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_CONTATO> CLIENTE_CONTATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_ENDERECO> CLIENTE_ENDERECO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_HISTORICO> CLIENTE_HISTORICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_MARKETING_ATIVO> CLIENTE_MARKETING_ATIVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_RESPOSTA> CLIENTE_RESPOSTA { get; set; }
        public virtual ORIGEM_CLIENTE ORIGEM_CLIENTE { get; set; }
        public virtual TIPO_CLIENTE TIPO_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEM_SERVICO> ORDEM_SERVICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PESQUISA_RESPOSTA> PESQUISA_RESPOSTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET_ATENDIMENTO> TICKET_ATENDIMENTO { get; set; }
    }
}
