//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_PERGUNTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE_PERGUNTA()
        {
            this.CLIENTE_PERGUNTA_OPCAO = new HashSet<CLIENTE_PERGUNTA_OPCAO>();
            this.CLIENTE_RESPOSTA = new HashSet<CLIENTE_RESPOSTA>();
        }
    
        public int CLPE_CD_ID { get; set; }
        public int TIRE_CD_ID { get; set; }
        public int TIIT_CD_ID { get; set; }
        public string CLPE_NM_PERGUNTA { get; set; }
        public int CLPE_IN_ATIVO { get; set; }
    
        public virtual TIPO_RESIDENCIA TIPO_RESIDENCIA { get; set; }
        public virtual TIPO_ITEM_PESQUISA TIPO_ITEM_PESQUISA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_PERGUNTA_OPCAO> CLIENTE_PERGUNTA_OPCAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_RESPOSTA> CLIENTE_RESPOSTA { get; set; }
    }
}
