//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRATO()
        {
            this.CONTRATO_ANEXOS = new HashSet<CONTRATO_ANEXOS>();
            this.CONTRATO_ANOTACOES = new HashSet<CONTRATO_ANOTACOES>();
        }
    
        public int CONT_CD_ID { get; set; }
        public int PARC_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public int TICO_CD_ID { get; set; }
        public int TISE_CD_ID { get; set; }
        public string CONT_NM_NOME { get; set; }
        public string CONT_NR_NUMERO { get; set; }
        public string CONT_DS_DESCRICAO { get; set; }
        public System.DateTime CONT_DT_CONTRATO { get; set; }
        public int CONT_NR_PRAZO_CONTRATO { get; set; }
        public System.DateTime CONT_DT_DATA_ACEITE { get; set; }
        public Nullable<int> CONT_QN_QUANTIDADE_ATENDIMENTOS { get; set; }
        public Nullable<decimal> CONT_VL_FAIXA_PRECO_INICIO { get; set; }
        public Nullable<decimal> CONT_VL_FAIXA_PRECO_FINAL { get; set; }
        public Nullable<int> CONT_NR_FREQUENCIA_UTILIZACAO { get; set; }
        public Nullable<decimal> CONT_VL_VALOR_MENSAL_APOLICE { get; set; }
        public Nullable<decimal> CONT_VL_VALOR_ANUAL_APOLICE { get; set; }
        public Nullable<int> CONT_NR_LIMITE_UTILIZACAO { get; set; }
        public Nullable<int> CONT_NR_LIMITE_COLETADOS { get; set; }
        public int CONT_IN_ATIVO { get; set; }
        public byte[] CONT_TX_OBSERVACAO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual TIPO_CONTRATO TIPO_CONTRATO { get; set; }
        public virtual TIPO_SERVICO TIPO_SERVICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO_ANEXOS> CONTRATO_ANEXOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO_ANOTACOES> CONTRATO_ANOTACOES { get; set; }
        public virtual PARCEIRO PARCEIRO { get; set; }
    }
}
