//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_PAGAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTA_PAGAR()
        {
            this.CONTA_PAGAR_RATEIO = new HashSet<CONTA_PAGAR_RATEIO>();
            this.CONTA_PAGAR_ANEXO = new HashSet<CONTA_PAGAR_ANEXO>();
            this.CONTA_PAGAR_PARCELA = new HashSet<CONTA_PAGAR_PARCELA>();
        }
    
        public int CAPA_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int PRES_CD_ID { get; set; }
        public int FOPA_CD_ID { get; set; }
        public int PERI_CD_ID { get; set; }
        public int ORSE_CD_ID { get; set; }
        public int CECU_CD_ID { get; set; }
        public System.DateTime CAPA_DT_LANCAMENTO { get; set; }
        public System.DateTime CAPA_DT_VENCIMENTO { get; set; }
        public Nullable<System.DateTime> CAPA_DT_LIQUIDACAO { get; set; }
        public Nullable<System.DateTime> CAPA_DT_INICIO_PARCELAS { get; set; }
        public System.DateTime CAPA_DT_COMPETENCIA { get; set; }
        public decimal CAPA_VL_VALOR { get; set; }
        public Nullable<decimal> CAPA_VL_VALOR_PAGO { get; set; }
        public Nullable<decimal> CAPA_VL_DESCONTO { get; set; }
        public Nullable<decimal> CAPA_VL_JUROS { get; set; }
        public Nullable<decimal> CAPA_VL_SALDO { get; set; }
        public Nullable<decimal> CAPA_VL_PARCIAL { get; set; }
        public string CAPA_DS_DESCRICAO { get; set; }
        public int CAPA_IN_LIQUIDADA { get; set; }
        public int CAPA_IN_PARCELADA { get; set; }
        public int CAPA_IN_PARCIAL { get; set; }
        public int CAPA_IN_ATIVO { get; set; }
        public Nullable<int> CAPA_IN_CHEQUE { get; set; }
        public int CAPA_NR_ATRASO { get; set; }
        public string CAPA_NR_CHEQUE { get; set; }
        public string CAPA_NR_DOCUMENTO { get; set; }
        public byte[] CAPA_TX_OBSERVACAO { get; set; }
    
        public virtual CENTRO_CUSTO CENTRO_CUSTO { get; set; }
        public virtual ORDEM_SERVICO ORDEM_SERVICO { get; set; }
        public virtual USUARIO_SUGESTAO USUARIO_SUGESTAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTA_PAGAR_RATEIO> CONTA_PAGAR_RATEIO { get; set; }
        public virtual FORM_PAGTO_RECTO FORM_PAGTO_RECTO { get; set; }
        public virtual PRESTADOR PRESTADOR { get; set; }
        public virtual PERIODICIDADE PERIODICIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTA_PAGAR_ANEXO> CONTA_PAGAR_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTA_PAGAR_PARCELA> CONTA_PAGAR_PARCELA { get; set; }
    }
}
