//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPARTAMENTO()
        {
            this.TICKET_ATENDIMENTO = new HashSet<TICKET_ATENDIMENTO>();
            this.USUARIO_SUGESTAO = new HashSet<USUARIO_SUGESTAO>();
        }
    
        public int DEPT_CD_ID { get; set; }
        public string DEPT_NM_NOME { get; set; }
        public string DEPT_SG_SIGLA { get; set; }
        public string DEPT_DS_DESCRICAO { get; set; }
        public int DEPT_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET_ATENDIMENTO> TICKET_ATENDIMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_SUGESTAO> USUARIO_SUGESTAO { get; set; }
    }
}
