//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESTINADOR_ENVIO_ANEXO
    {
        public int DENX_CD_ID { get; set; }
        public int DEEN_CD_ID { get; set; }
        public System.DateTime DENX_DT_ANEXO { get; set; }
        public int DENX_IN_TIPO { get; set; }
        public string DENX_NM_TITULO { get; set; }
        public string DENX_AQ_ARQUIVO { get; set; }
        public int DENX_IN_ATIVO { get; set; }
    
        public virtual DESTINADOR_ENVIO DESTINADOR_ENVIO { get; set; }
    }
}
