//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESTINADOR_ENVIO_PRODUTO
    {
        public int DEEP_CD_ID { get; set; }
        public int DEEN_CD_ID { get; set; }
        public int OSPD_CD_ID { get; set; }
        public int TIRE_CD_ID { get; set; }
        public int UNID_CD_ID { get; set; }
        public int ESFI_CD_ID { get; set; }
        public Nullable<int> DEEP_QN_QUANTIDADE { get; set; }
        public string DEEP_DS_ESTADO_FISICO_DESCRICAO { get; set; }
        public int CLASS_CD_ID { get; set; }
        public int ACON_CD_ID { get; set; }
        public int TRAT_CD_ID { get; set; }
        public string DEEP_DS_TRATAMENTO_DESCRICAO { get; set; }
        public byte[] DEEP_TX_OBSERVACAO { get; set; }
        public Nullable<int> DEEP_IN_ATIVO { get; set; }
    
        public virtual ACONDICIONAMENTO ACONDICIONAMENTO { get; set; }
        public virtual CLASSE CLASSE { get; set; }
        public virtual DESTINADOR_ENVIO DESTINADOR_ENVIO { get; set; }
        public virtual ORDEM_SERVICO_PRODUTO ORDEM_SERVICO_PRODUTO { get; set; }
        public virtual TIPO_RESIDUO TIPO_RESIDUO { get; set; }
        public virtual TRATAMENTO TRATAMENTO { get; set; }
        public virtual ESTADO_FISICO ESTADO_FISICO { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
    }
}
