//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESTINADOR_ANEXO
    {
        public int DEAX_CD_ID { get; set; }
        public int DEST_CD_ID { get; set; }
        public System.DateTime DEAX_DT_ANEXO { get; set; }
        public int DEAX_IN_TIPO { get; set; }
        public string DEAX_NM_TITULO { get; set; }
        public string DEAX_AQ_ARQUIVO { get; set; }
        public int DEAX_IN_ATIVO { get; set; }
    
        public virtual DESTINADOR DESTINADOR { get; set; }
    }
}
