//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_EcoBaseEntities : DbContext
    {
        public DB_EcoBaseEntities()
            : base("name=DB_EcoBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACONDICIONAMENTO> ACONDICIONAMENTO { get; set; }
        public virtual DbSet<ATENDIMENTO_ACOMPANHAMENTO> ATENDIMENTO_ACOMPANHAMENTO { get; set; }
        public virtual DbSet<ATENDIMENTO_ANEXO> ATENDIMENTO_ANEXO { get; set; }
        public virtual DbSet<ATENDIMENTO_STATUS> ATENDIMENTO_STATUS { get; set; }
        public virtual DbSet<AUDITORIA> AUDITORIA { get; set; }
        public virtual DbSet<BANCO> BANCO { get; set; }
        public virtual DbSet<CARGO> CARGO { get; set; }
        public virtual DbSet<CATEGORIA_ATENDIMENTO> CATEGORIA_ATENDIMENTO { get; set; }
        public virtual DbSet<CATEGORIA_FORNECEDOR> CATEGORIA_FORNECEDOR { get; set; }
        public virtual DbSet<CATEGORIA_NOTIFICACAO> CATEGORIA_NOTIFICACAO { get; set; }
        public virtual DbSet<CATEGORIA_PRODUTO> CATEGORIA_PRODUTO { get; set; }
        public virtual DbSet<CATEGORIA_USUARIO> CATEGORIA_USUARIO { get; set; }
        public virtual DbSet<CENTRO_CUSTO> CENTRO_CUSTO { get; set; }
        public virtual DbSet<CLASSE> CLASSE { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CLIENTE_ANEXO> CLIENTE_ANEXO { get; set; }
        public virtual DbSet<CLIENTE_APOLICE> CLIENTE_APOLICE { get; set; }
        public virtual DbSet<CLIENTE_CONTATO> CLIENTE_CONTATO { get; set; }
        public virtual DbSet<CLIENTE_ENDERECO> CLIENTE_ENDERECO { get; set; }
        public virtual DbSet<CLIENTE_HISTORICO> CLIENTE_HISTORICO { get; set; }
        public virtual DbSet<CLIENTE_MARKETING_ATIVO> CLIENTE_MARKETING_ATIVO { get; set; }
        public virtual DbSet<CLIENTE_PERGUNTA> CLIENTE_PERGUNTA { get; set; }
        public virtual DbSet<CLIENTE_PERGUNTA_OPCAO> CLIENTE_PERGUNTA_OPCAO { get; set; }
        public virtual DbSet<CLIENTE_RESPOSTA> CLIENTE_RESPOSTA { get; set; }
        public virtual DbSet<CNH_CATEGORIA> CNH_CATEGORIA { get; set; }
        public virtual DbSet<CONTA_BANCO> CONTA_BANCO { get; set; }
        public virtual DbSet<CONTA_BANCO_ANEXO> CONTA_BANCO_ANEXO { get; set; }
        public virtual DbSet<CONTA_BANCO_CONTATO> CONTA_BANCO_CONTATO { get; set; }
        public virtual DbSet<CONTA_BANCO_LANCAMENTO> CONTA_BANCO_LANCAMENTO { get; set; }
        public virtual DbSet<CONTA_PAGAR> CONTA_PAGAR { get; set; }
        public virtual DbSet<CONTA_PAGAR_ANEXO> CONTA_PAGAR_ANEXO { get; set; }
        public virtual DbSet<CONTA_PAGAR_PARCELA> CONTA_PAGAR_PARCELA { get; set; }
        public virtual DbSet<CONTA_PAGAR_RATEIO> CONTA_PAGAR_RATEIO { get; set; }
        public virtual DbSet<CONTA_RECEBER> CONTA_RECEBER { get; set; }
        public virtual DbSet<CONTA_RECEBER_ANEXO> CONTA_RECEBER_ANEXO { get; set; }
        public virtual DbSet<CONTA_RECEBER_PARCELA> CONTA_RECEBER_PARCELA { get; set; }
        public virtual DbSet<CONTA_RECEBER_RATEIO> CONTA_RECEBER_RATEIO { get; set; }
        public virtual DbSet<CONTRATO> CONTRATO { get; set; }
        public virtual DbSet<CONTRATO_ANEXOS> CONTRATO_ANEXOS { get; set; }
        public virtual DbSet<CONTRATO_ANOTACOES> CONTRATO_ANOTACOES { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<DESTINADOR> DESTINADOR { get; set; }
        public virtual DbSet<DESTINADOR_ANEXO> DESTINADOR_ANEXO { get; set; }
        public virtual DbSet<DESTINADOR_ANOTACOES> DESTINADOR_ANOTACOES { get; set; }
        public virtual DbSet<DESTINADOR_ENVIO> DESTINADOR_ENVIO { get; set; }
        public virtual DbSet<DESTINADOR_ENVIO_ANEXO> DESTINADOR_ENVIO_ANEXO { get; set; }
        public virtual DbSet<DESTINADOR_ENVIO_ANOTACOES> DESTINADOR_ENVIO_ANOTACOES { get; set; }
        public virtual DbSet<DESTINADOR_ENVIO_PRODUTO> DESTINADOR_ENVIO_PRODUTO { get; set; }
        public virtual DbSet<ESTADO_FISICO> ESTADO_FISICO { get; set; }
        public virtual DbSet<FORM_PAGTO_RECTO> FORM_PAGTO_RECTO { get; set; }
        public virtual DbSet<FORNECEDOR> FORNECEDOR { get; set; }
        public virtual DbSet<GRUPO> GRUPO { get; set; }
        public virtual DbSet<ITEM_PEDIDO_COMPRA> ITEM_PEDIDO_COMPRA { get; set; }
        public virtual DbSet<LEILOEIRO> LEILOEIRO { get; set; }
        public virtual DbSet<LEILOEIRO_LOTE> LEILOEIRO_LOTE { get; set; }
        public virtual DbSet<LEILOEIRO_LOTE_ITENS> LEILOEIRO_LOTE_ITENS { get; set; }
        public virtual DbSet<LINHA_PRODUTO> LINHA_PRODUTO { get; set; }
        public virtual DbSet<MARCA_VEICULO> MARCA_VEICULO { get; set; }
        public virtual DbSet<MODELO_VEICULO> MODELO_VEICULO { get; set; }
        public virtual DbSet<MOTIVO_FALHA_ORDEM_SERVICO> MOTIVO_FALHA_ORDEM_SERVICO { get; set; }
        public virtual DbSet<NOTICIA> NOTICIA { get; set; }
        public virtual DbSet<NOTICIA_COMENTARIO> NOTICIA_COMENTARIO { get; set; }
        public virtual DbSet<NOTIFICACAO> NOTIFICACAO { get; set; }
        public virtual DbSet<NOTIFICACAO_ANEXO> NOTIFICACAO_ANEXO { get; set; }
        public virtual DbSet<ORDEM_SERVICO> ORDEM_SERVICO { get; set; }
        public virtual DbSet<ORDEM_SERVICO_AGENDAMENTO> ORDEM_SERVICO_AGENDAMENTO { get; set; }
        public virtual DbSet<ORDEM_SERVICO_AGENDAMENTO_ANOTACAO> ORDEM_SERVICO_AGENDAMENTO_ANOTACAO { get; set; }
        public virtual DbSet<ORDEM_SERVICO_ANEXO> ORDEM_SERVICO_ANEXO { get; set; }
        public virtual DbSet<ORDEM_SERVICO_ANOTACAO> ORDEM_SERVICO_ANOTACAO { get; set; }
        public virtual DbSet<ORDEM_SERVICO_HISTORICO> ORDEM_SERVICO_HISTORICO { get; set; }
        public virtual DbSet<ORDEM_SERVICO_PRESTADOR> ORDEM_SERVICO_PRESTADOR { get; set; }
        public virtual DbSet<ORDEM_SERVICO_PRODUTO> ORDEM_SERVICO_PRODUTO { get; set; }
        public virtual DbSet<ORDEM_SERVICO_PROPOSTA> ORDEM_SERVICO_PROPOSTA { get; set; }
        public virtual DbSet<ORDEM_SERVICO_PROPOSTA_ANEXO> ORDEM_SERVICO_PROPOSTA_ANEXO { get; set; }
        public virtual DbSet<ORIGEM> ORIGEM { get; set; }
        public virtual DbSet<ORIGEM_CLIENTE> ORIGEM_CLIENTE { get; set; }
        public virtual DbSet<PARCEIRO> PARCEIRO { get; set; }
        public virtual DbSet<PARCEIRO_CONTATO> PARCEIRO_CONTATO { get; set; }
        public virtual DbSet<PARCEIRO_ENDERECO> PARCEIRO_ENDERECO { get; set; }
        public virtual DbSet<PARCEIRO_PRECO> PARCEIRO_PRECO { get; set; }
        public virtual DbSet<PEDIDO_COMPRA> PEDIDO_COMPRA { get; set; }
        public virtual DbSet<PEDIDO_COMPRA_ACOMPANHAMENTO> PEDIDO_COMPRA_ACOMPANHAMENTO { get; set; }
        public virtual DbSet<PEDIDO_COMPRA_ANEXO> PEDIDO_COMPRA_ANEXO { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<PERIODICIDADE> PERIODICIDADE { get; set; }
        public virtual DbSet<PERIODO> PERIODO { get; set; }
        public virtual DbSet<PESQUISA> PESQUISA { get; set; }
        public virtual DbSet<PESQUISA_ITEM> PESQUISA_ITEM { get; set; }
        public virtual DbSet<PESQUISA_ITEM_OPCAO> PESQUISA_ITEM_OPCAO { get; set; }
        public virtual DbSet<PESQUISA_RESPOSTA> PESQUISA_RESPOSTA { get; set; }
        public virtual DbSet<PESQUISA_RESPOSTA_ITEM> PESQUISA_RESPOSTA_ITEM { get; set; }
        public virtual DbSet<PORTE> PORTE { get; set; }
        public virtual DbSet<PRESTADOR> PRESTADOR { get; set; }
        public virtual DbSet<PRESTADOR_AJUDANTE> PRESTADOR_AJUDANTE { get; set; }
        public virtual DbSet<PRESTADOR_AJUDANTE_ANOTACOES> PRESTADOR_AJUDANTE_ANOTACOES { get; set; }
        public virtual DbSet<PRESTADOR_ANEXO> PRESTADOR_ANEXO { get; set; }
        public virtual DbSet<PRESTADOR_ANOTACOES> PRESTADOR_ANOTACOES { get; set; }
        public virtual DbSet<PRESTADOR_BANCO> PRESTADOR_BANCO { get; set; }
        public virtual DbSet<PRESTADOR_CERTIFICADO> PRESTADOR_CERTIFICADO { get; set; }
        public virtual DbSet<PRESTADOR_CONTATO> PRESTADOR_CONTATO { get; set; }
        public virtual DbSet<PRESTADOR_ENDERECO> PRESTADOR_ENDERECO { get; set; }
        public virtual DbSet<PRESTADOR_ENDERECO_ESTOQUE> PRESTADOR_ENDERECO_ESTOQUE { get; set; }
        public virtual DbSet<PRESTADOR_ENDERECO_VERIFICACAO> PRESTADOR_ENDERECO_VERIFICACAO { get; set; }
        public virtual DbSet<PRESTADOR_MOTORISTA> PRESTADOR_MOTORISTA { get; set; }
        public virtual DbSet<PRESTADOR_MOTORISTA_ANOTACOES> PRESTADOR_MOTORISTA_ANOTACOES { get; set; }
        public virtual DbSet<PRESTADOR_REGIAO> PRESTADOR_REGIAO { get; set; }
        public virtual DbSet<PRESTADOR_VEICULO> PRESTADOR_VEICULO { get; set; }
        public virtual DbSet<PRESTADOR_VEICULO_ANOTACOES> PRESTADOR_VEICULO_ANOTACOES { get; set; }
        public virtual DbSet<PRESTADOR_VEICULO_CERTIFICADO> PRESTADOR_VEICULO_CERTIFICADO { get; set; }
        public virtual DbSet<PRESTADOR_VEICULO_FUNCAO> PRESTADOR_VEICULO_FUNCAO { get; set; }
        public virtual DbSet<PRODUTO_COMPRA> PRODUTO_COMPRA { get; set; }
        public virtual DbSet<PRODUTO_PERGUNTAS> PRODUTO_PERGUNTAS { get; set; }
        public virtual DbSet<PRODUTO_PERGUNTAS_OPCAO> PRODUTO_PERGUNTAS_OPCAO { get; set; }
        public virtual DbSet<PRODUTOS_RESPOSTA> PRODUTOS_RESPOSTA { get; set; }
        public virtual DbSet<PROPOSTA> PROPOSTA { get; set; }
        public virtual DbSet<REGIAO> REGIAO { get; set; }
        public virtual DbSet<REGIAO_COBERTURA> REGIAO_COBERTURA { get; set; }
        public virtual DbSet<STATUS_COLETA> STATUS_COLETA { get; set; }
        public virtual DbSet<STATUS_ORDEM_SERVICO> STATUS_ORDEM_SERVICO { get; set; }
        public virtual DbSet<SUBCATEGORIA_PRODUTO> SUBCATEGORIA_PRODUTO { get; set; }
        public virtual DbSet<SUBGRUPO> SUBGRUPO { get; set; }
        public virtual DbSet<TEMPLATE_MENSAGEM> TEMPLATE_MENSAGEM { get; set; }
        public virtual DbSet<TICKET_ATENDIMENTO> TICKET_ATENDIMENTO { get; set; }
        public virtual DbSet<TIPO_CENTRO_CUSTO> TIPO_CENTRO_CUSTO { get; set; }
        public virtual DbSet<TIPO_CERTIFICADO> TIPO_CERTIFICADO { get; set; }
        public virtual DbSet<TIPO_CERTIFICADO_VEICULO> TIPO_CERTIFICADO_VEICULO { get; set; }
        public virtual DbSet<TIPO_CLIENTE> TIPO_CLIENTE { get; set; }
        public virtual DbSet<TIPO_CONTA> TIPO_CONTA { get; set; }
        public virtual DbSet<TIPO_CONTRATO> TIPO_CONTRATO { get; set; }
        public virtual DbSet<TIPO_ITEM_PESQUISA> TIPO_ITEM_PESQUISA { get; set; }
        public virtual DbSet<TIPO_ORDEM_SERVICO> TIPO_ORDEM_SERVICO { get; set; }
        public virtual DbSet<TIPO_PARCEIRO> TIPO_PARCEIRO { get; set; }
        public virtual DbSet<TIPO_PESQUISA> TIPO_PESQUISA { get; set; }
        public virtual DbSet<TIPO_PESSOA> TIPO_PESSOA { get; set; }
        public virtual DbSet<TIPO_PRODUTO> TIPO_PRODUTO { get; set; }
        public virtual DbSet<TIPO_RESIDENCIA> TIPO_RESIDENCIA { get; set; }
        public virtual DbSet<TIPO_RESIDUO> TIPO_RESIDUO { get; set; }
        public virtual DbSet<TIPO_SERVICO> TIPO_SERVICO { get; set; }
        public virtual DbSet<TIPO_VEICULO> TIPO_VEICULO { get; set; }
        public virtual DbSet<TRATAMENTO> TRATAMENTO { get; set; }
        public virtual DbSet<UF> UF { get; set; }
        public virtual DbSet<UNIDADE> UNIDADE { get; set; }
        public virtual DbSet<USUARIO_ANEXO> USUARIO_ANEXO { get; set; }
        public virtual DbSet<USUARIO_SUGESTAO> USUARIO_SUGESTAO { get; set; }
        public virtual DbSet<VEICULO_FUNCAO> VEICULO_FUNCAO { get; set; }
        public virtual DbSet<AGENDA> AGENDA { get; set; }
        public virtual DbSet<AGENDA_ANEXO> AGENDA_ANEXO { get; set; }
        public virtual DbSet<AGENDA_VINCULO> AGENDA_VINCULO { get; set; }
        public virtual DbSet<CATEGORIA_AGENDA> CATEGORIA_AGENDA { get; set; }
        public virtual DbSet<CATEGORIA_TELEFONE> CATEGORIA_TELEFONE { get; set; }
        public virtual DbSet<PERIODICIDADE_TAREFA> PERIODICIDADE_TAREFA { get; set; }
        public virtual DbSet<TAREFA> TAREFA { get; set; }
        public virtual DbSet<TAREFA_ACOMPANHAMENTO> TAREFA_ACOMPANHAMENTO { get; set; }
        public virtual DbSet<TAREFA_ANEXO> TAREFA_ANEXO { get; set; }
        public virtual DbSet<TAREFA_NOTIFICACAO> TAREFA_NOTIFICACAO { get; set; }
        public virtual DbSet<TAREFA_VINCULO> TAREFA_VINCULO { get; set; }
        public virtual DbSet<TELEFONE> TELEFONE { get; set; }
        public virtual DbSet<TEMPLATE> TEMPLATE { get; set; }
        public virtual DbSet<TEMPLATE_EMAIL> TEMPLATE_EMAIL { get; set; }
        public virtual DbSet<TEMPLATE_SMS> TEMPLATE_SMS { get; set; }
        public virtual DbSet<TIPO_TAREFA> TIPO_TAREFA { get; set; }
        public virtual DbSet<CONFIGURACAO> CONFIGURACAO { get; set; }
        public virtual DbSet<LOG> LOG { get; set; }
    }
}
