//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEILOEIRO_LOTE_ITENS
    {
        public int LELI_CD_ID { get; set; }
        public int LELO_CD_ID { get; set; }
        public int OSPD_CD_ID { get; set; }
        public string LELI_DS_OBSERVACOES { get; set; }
        public int LELI_IN_ATIVO { get; set; }
    
        public virtual LEILOEIRO_LOTE LEILOEIRO_LOTE { get; set; }
        public virtual ORDEM_SERVICO_PRODUTO ORDEM_SERVICO_PRODUTO { get; set; }
    }
}
