//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEILOEIRO_LOTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LEILOEIRO_LOTE()
        {
            this.LEILOEIRO_LOTE_ITENS = new HashSet<LEILOEIRO_LOTE_ITENS>();
        }
    
        public int LELO_CD_ID { get; set; }
        public int LEIL_CD_ID { get; set; }
        public string LELO_NR_LOTE { get; set; }
        public string LELO_NM_LOTE { get; set; }
        public System.DateTime LELO_DT_LOTE { get; set; }
        public int LELO_IN_ATIVO { get; set; }
    
        public virtual LEILOEIRO LEILOEIRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEILOEIRO_LOTE_ITENS> LEILOEIRO_LOTE_ITENS { get; set; }
    }
}
