//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEILOEIRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LEILOEIRO()
        {
            this.LEILOEIRO_LOTE = new HashSet<LEILOEIRO_LOTE>();
        }
    
        public int LEIL_CD_ID { get; set; }
        public string LEIL_NM_NOME { get; set; }
        public string LEIL_NR_CNPJ { get; set; }
        public string LEIL_NM_ENDERECO { get; set; }
        public string LEIL_NR_NUMERO { get; set; }
        public string LEIL_NM_COMPLEMENTO { get; set; }
        public string LEIL_NM_BAIRRO { get; set; }
        public string LEIL_NM_CIDADE { get; set; }
        public string LEIL_NR_CEP { get; set; }
        public int UF_CD_ID { get; set; }
        public int LEIL_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEILOEIRO_LOTE> LEILOEIRO_LOTE { get; set; }
        public virtual UF UF { get; set; }
    }
}
