//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEM_SERVICO_PRESTADOR
    {
        public int OSPR_CD_ID { get; set; }
        public int ORSE_CD_ID { get; set; }
        public int PRES_CD_ID { get; set; }
        public int PRMO_CD_ID { get; set; }
        public int OSPR_IN_ESTOQUE { get; set; }
        public int PRAJ_CD_ID { get; set; }
        public int PRVE_CD_ID { get; set; }
        public int OSPR_IN_ATIVO { get; set; }
    
        public virtual ORDEM_SERVICO ORDEM_SERVICO { get; set; }
        public virtual PRESTADOR_VEICULO PRESTADOR_VEICULO { get; set; }
        public virtual PRESTADOR PRESTADOR { get; set; }
        public virtual PRESTADOR_MOTORISTA PRESTADOR_MOTORISTA { get; set; }
        public virtual PRESTADOR_AJUDANTE PRESTADOR_AJUDANTE { get; set; }
    }
}
