//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEM_SERVICO_ANOTACAO
    {
        public int OSAN_CD_ID { get; set; }
        public int ORSE_CD_ID { get; set; }
        public System.DateTime OSAN_DT_ANOTACAO { get; set; }
        public int USUA_CD_ID { get; set; }
        public byte[] OSAN_TX_ANOTACAO { get; set; }
        public string OSAN_TX_TEXTO_ANOTACAO { get; set; }
    
        public virtual ORDEM_SERVICO ORDEM_SERVICO { get; set; }
        public virtual USUARIO_SUGESTAO USUARIO_SUGESTAO { get; set; }
    }
}
