//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEM_SERVICO_PROPOSTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEM_SERVICO_PROPOSTA()
        {
            this.ORDEM_SERVICO_PROPOSTA_ANEXO = new HashSet<ORDEM_SERVICO_PROPOSTA_ANEXO>();
        }
    
        public int OSPP_CD_ID { get; set; }
        public int ORSE_CD_ID { get; set; }
        public Nullable<int> PROP_CD_ID { get; set; }
        public System.DateTime OSPP_DT_PROPOSTA { get; set; }
        public string OSPP_NR_PROPOSTA { get; set; }
        public int OSPP_IN_ATIVO { get; set; }
        public string OSPR_TX_TEXTO { get; set; }
    
        public virtual ORDEM_SERVICO ORDEM_SERVICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEM_SERVICO_PROPOSTA_ANEXO> ORDEM_SERVICO_PROPOSTA_ANEXO { get; set; }
        public virtual PROPOSTA PROPOSTA { get; set; }
    }
}
