//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEM_SERVICO_AGENDAMENTO
    {
        public int OSAG_CD_ID { get; set; }
        public int ORSE_CD_ID { get; set; }
        public System.DateTime OSAG_DT_AGENDAMENTO { get; set; }
        public int PERI_CD_ID { get; set; }
        public int OSAG_IN_LIBERADA { get; set; }
        public int STCO_CD_ID { get; set; }
        public Nullable<System.TimeSpan> OSAG_HR_CHEGADA_CLIENTE { get; set; }
        public Nullable<System.TimeSpan> OSAG_HR_SAIDA_CLIENTE { get; set; }
        public Nullable<int> OSAG_IN_TIPO_FALHA { get; set; }
        public int MFOS_CD_ID { get; set; }
        public string OSAG_DS_JUSTIFICATIVA { get; set; }
        public int OSAG_IN_CRIADO_POR { get; set; }
        public System.DateTime OSAG_DT_CRIADO_EM { get; set; }
        public int OSAG_IN_ATIVO { get; set; }
    
        public virtual MOTIVO_FALHA_ORDEM_SERVICO MOTIVO_FALHA_ORDEM_SERVICO { get; set; }
        public virtual ORDEM_SERVICO ORDEM_SERVICO { get; set; }
        public virtual USUARIO_SUGESTAO USUARIO_SUGESTAO { get; set; }
        public virtual PERIODO PERIODO { get; set; }
        public virtual STATUS_COLETA STATUS_COLETA { get; set; }
    }
}
