//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEM_SERVICO_PROPOSTA_ANEXO
    {
        public int OSPA_CD_ID { get; set; }
        public int OSPP_CD_ID { get; set; }
        public System.DateTime OSPA_DT_ANEXO { get; set; }
        public string OSPA_NM_TITULO { get; set; }
        public int OSPA_IN_TIPO { get; set; }
        public string OSPA_AQ_ARQUIVO { get; set; }
        public int OSPA_IN_ATIVO { get; set; }
    
        public virtual ORDEM_SERVICO_PROPOSTA ORDEM_SERVICO_PROPOSTA { get; set; }
    }
}
