//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARCEIRO_PRECO
    {
        public int PAPR_CD_ID { get; set; }
        public int PARC_CD_ID { get; set; }
        public int TIPR_CD_ID { get; set; }
        public int PORT_CD_ID { get; set; }
        public int LIPR_CD_ID { get; set; }
        public int PAPR_IN_TIPO { get; set; }
        public int PAPR_IN_QUANTIDADE_MINIMA { get; set; }
        public decimal PAPR_VL_PRECO { get; set; }
        public decimal PAPR_VL_VALOR_UNITARIO { get; set; }
        public int PAPR_IN_ATIVO { get; set; }
    
        public virtual LINHA_PRODUTO LINHA_PRODUTO { get; set; }
        public virtual PARCEIRO PARCEIRO { get; set; }
        public virtual PORTE PORTE { get; set; }
        public virtual TIPO_PRODUTO TIPO_PRODUTO { get; set; }
    }
}
