//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARCEIRO_CONTATO
    {
        public int PACO_CD_ID { get; set; }
        public int PARC_CD_ID { get; set; }
        public string PACO_NM_NOME { get; set; }
        public string PACO_NM_CARGO { get; set; }
        public string PACO_EM_EMAIL { get; set; }
        public string PACO_NR_TELEFONE { get; set; }
        public string PACO_NR_CELULAR { get; set; }
        public string PACO_NR_WHATSAPP { get; set; }
        public int PACO_IN_ATIVO { get; set; }
    
        public virtual PARCEIRO PARCEIRO { get; set; }
    }
}
