//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARCEIRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARCEIRO()
        {
            this.CLIENTE_APOLICE = new HashSet<CLIENTE_APOLICE>();
            this.CONTA_RECEBER = new HashSet<CONTA_RECEBER>();
            this.CONTRATO = new HashSet<CONTRATO>();
            this.ORDEM_SERVICO = new HashSet<ORDEM_SERVICO>();
            this.ORDEM_SERVICO_PRODUTO = new HashSet<ORDEM_SERVICO_PRODUTO>();
            this.PARCEIRO_CONTATO = new HashSet<PARCEIRO_CONTATO>();
            this.PARCEIRO_ENDERECO = new HashSet<PARCEIRO_ENDERECO>();
            this.PARCEIRO_PRECO = new HashSet<PARCEIRO_PRECO>();
        }
    
        public int PARC_CD_ID { get; set; }
        public int TIPA_CD_ID { get; set; }
        public string PARC_NM_NOME { get; set; }
        public string PARC_NR_CNPJ { get; set; }
        public string PARC_NM_CONTATO_PRINCIPAL { get; set; }
        public string PARC_NM_CARGO_PRINCIPAL { get; set; }
        public string PARC_EM_EMAIL_PRINCIPAL { get; set; }
        public string PARC_NR_TELEFONE_PRINCIPAL { get; set; }
        public string PARC_NR_CELULAR_PRINCIPAL { get; set; }
        public string PARC_NR_WHATSAPP_PRINCIPAL { get; set; }
        public string PARC_NM_WEBSITE { get; set; }
        public int PARC_IN_STATUS { get; set; }
        public byte[] PARC_TX_OBSERVACOES { get; set; }
        public System.DateTime PARC_DT_CADASTRO { get; set; }
        public int PARC_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_APOLICE> CLIENTE_APOLICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTA_RECEBER> CONTA_RECEBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEM_SERVICO> ORDEM_SERVICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEM_SERVICO_PRODUTO> ORDEM_SERVICO_PRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARCEIRO_CONTATO> PARCEIRO_CONTATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARCEIRO_ENDERECO> PARCEIRO_ENDERECO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARCEIRO_PRECO> PARCEIRO_PRECO { get; set; }
        public virtual TIPO_PARCEIRO TIPO_PARCEIRO { get; set; }
    }
}
