//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARCEIRO_ENDERECO
    {
        public int PAEN_CD_ID { get; set; }
        public int PARC_CD_ID { get; set; }
        public string PAEN_NM_ENDERECO { get; set; }
        public string PAEN_NR_NUMERO { get; set; }
        public string PAEN_NM_COMPLEMENTO { get; set; }
        public string PAEN_NM_BAIRRO { get; set; }
        public string PAEN_NM_CIDADE { get; set; }
        public string PAEN_NR_CEP { get; set; }
        public int UF_CD_ID { get; set; }
        public byte[] PAEN_TX_REFERENCIA_LOCAL { get; set; }
        public int PAEN_IN_ATIVO { get; set; }
    
        public virtual PARCEIRO PARCEIRO { get; set; }
        public virtual UF UF { get; set; }
    }
}
