//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_COMPRA_ANEXO
    {
        public int PCAN_CD_ID { get; set; }
        public int PECO_CD_ID { get; set; }
        public System.DateTime PCAN_DT_ANEXO { get; set; }
        public int PCAN_IN_TIPO { get; set; }
        public string PCAN_AQ_ARQUIVO { get; set; }
        public int PCAN_IN_ATIVO { get; set; }
    
        public virtual PEDIDO_COMPRA PEDIDO_COMPRA { get; set; }
    }
}
