//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESQUISA_RESPOSTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PESQUISA_RESPOSTA()
        {
            this.PESQUISA_RESPOSTA_ITEM = new HashSet<PESQUISA_RESPOSTA_ITEM>();
        }
    
        public int PERE_CD_ID { get; set; }
        public int PESQ_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public System.DateTime PERE_DT_RESPOSTA { get; set; }
        public int PERE_IN_ATIVO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PESQUISA PESQUISA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PESQUISA_RESPOSTA_ITEM> PESQUISA_RESPOSTA_ITEM { get; set; }
    }
}
