//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESQUISA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PESQUISA()
        {
            this.PESQUISA_ITEM = new HashSet<PESQUISA_ITEM>();
            this.PESQUISA_RESPOSTA = new HashSet<PESQUISA_RESPOSTA>();
        }
    
        public int PESQ_CD_ID { get; set; }
        public int TIPS_CD_ID { get; set; }
        public string PESQ_NM_NOME { get; set; }
        public string PESQ_DS_DESCRICAO { get; set; }
        public System.DateTime PESQ_DT_CRIACAO { get; set; }
        public System.DateTime PESQ_DT_VALIDADE { get; set; }
        public byte[] PESQ_TX_OBSERVACAO { get; set; }
        public int PESQ_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PESQUISA_ITEM> PESQUISA_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PESQUISA_RESPOSTA> PESQUISA_RESPOSTA { get; set; }
        public virtual TIPO_PESQUISA TIPO_PESQUISA { get; set; }
    }
}
