//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTADOR_ANOTACOES
    {
        public int PRAN_CD_ID { get; set; }
        public int PRES_CD_ID { get; set; }
        public System.DateTime PRAN_DT_ANOTACAO { get; set; }
        public int USUA_CD_ID { get; set; }
        public string PRAN_TX_ANOTACAO { get; set; }
    
        public virtual PRESTADOR PRESTADOR { get; set; }
        public virtual USUARIO_SUGESTAO USUARIO_SUGESTAO { get; set; }
    }
}
