//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTADOR_CONTATO
    {
        public int PRCO_CD_ID { get; set; }
        public int PRES_CD_ID { get; set; }
        public string PRCO_NM_NOME { get; set; }
        public string PRCO_NM_CARGO { get; set; }
        public string PRCO_EM_EMAIL { get; set; }
        public string PRCO_NR_TELEFONE { get; set; }
        public string PRCO_NR_CELULAR { get; set; }
        public string PRCO_NR_WHATSAPP { get; set; }
        public int PRCO_IN_ATIVO { get; set; }
    
        public virtual PRESTADOR PRESTADOR { get; set; }
    }
}
