//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTADOR_VEICULO_ANOTACOES
    {
        public int PRVA_CD_ID { get; set; }
        public int PRVE_CD_ID { get; set; }
        public System.DateTime PRVA_DT_ANOTACAO { get; set; }
        public int USUA_CD_ID { get; set; }
        public byte[] PRVA_TX_ANOTACAO { get; set; }
    
        public virtual PRESTADOR_VEICULO PRESTADOR_VEICULO { get; set; }
        public virtual USUARIO_SUGESTAO USUARIO_SUGESTAO { get; set; }
    }
}
