//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTADOR_AJUDANTE_ANOTACOES
    {
        public int PRAA_CD_ID { get; set; }
        public int PRAJ_CD_ID { get; set; }
        public System.DateTime PRAA_DT_ANOTACAO { get; set; }
        public int USUA_CD_ID { get; set; }
        public string PRAA_TX_ANOTACAO { get; set; }
    
        public virtual PRESTADOR_AJUDANTE PRESTADOR_AJUDANTE { get; set; }
        public virtual USUARIO_SUGESTAO USUARIO_SUGESTAO { get; set; }
    }
}
