//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTADOR_ENDERECO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRESTADOR_ENDERECO()
        {
            this.PRESTADOR_ENDERECO_ESTOQUE = new HashSet<PRESTADOR_ENDERECO_ESTOQUE>();
        }
    
        public int PREN_CD_ID { get; set; }
        public int PRES_CD_ID { get; set; }
        public string PREN_NM_ENDERECO { get; set; }
        public string PRE_NR_NUMERO { get; set; }
        public string PREN_NM_COMPLEMENTO { get; set; }
        public string PREN_NM_BAIRRO { get; set; }
        public string PREN_NM_CIDADE { get; set; }
        public string PREN_NR_CEP { get; set; }
        public int UF_CD_ID { get; set; }
        public int PREN_IN_FLAG_ESTOQUE { get; set; }
        public string PREN_NM_NOME_ESTOQUE { get; set; }
        public int PREN_IN_ATIVO { get; set; }
        public string PREN_DS_REFERENCIA_LOCAL { get; set; }
    
        public virtual PRESTADOR PRESTADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTADOR_ENDERECO_ESTOQUE> PRESTADOR_ENDERECO_ESTOQUE { get; set; }
        public virtual UF UF { get; set; }
    }
}
