//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTADOR_VEICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRESTADOR_VEICULO()
        {
            this.ORDEM_SERVICO_PRESTADOR = new HashSet<ORDEM_SERVICO_PRESTADOR>();
            this.PRESTADOR_VEICULO_FUNCAO = new HashSet<PRESTADOR_VEICULO_FUNCAO>();
            this.PRESTADOR_VEICULO_ANOTACOES = new HashSet<PRESTADOR_VEICULO_ANOTACOES>();
            this.PRESTADOR_VEICULO_CERTIFICADO = new HashSet<PRESTADOR_VEICULO_CERTIFICADO>();
        }
    
        public int PRVE_CD_ID { get; set; }
        public int PRES_CD_ID { get; set; }
        public int TIVE_CD_ID { get; set; }
        public int MOVE_CD_ID { get; set; }
        public int MAVE_CD_ID { get; set; }
        public string PRVE_NR_PLACA { get; set; }
        public Nullable<int> PRVE_NR_CAPACIDADE { get; set; }
        public string PRVE_AQ_FOTO { get; set; }
        public int PRVE_IN_ATIVO { get; set; }
    
        public virtual MARCA_VEICULO MARCA_VEICULO { get; set; }
        public virtual MODELO_VEICULO MODELO_VEICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEM_SERVICO_PRESTADOR> ORDEM_SERVICO_PRESTADOR { get; set; }
        public virtual PRESTADOR PRESTADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTADOR_VEICULO_FUNCAO> PRESTADOR_VEICULO_FUNCAO { get; set; }
        public virtual TIPO_VEICULO TIPO_VEICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTADOR_VEICULO_ANOTACOES> PRESTADOR_VEICULO_ANOTACOES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTADOR_VEICULO_CERTIFICADO> PRESTADOR_VEICULO_CERTIFICADO { get; set; }
    }
}
