//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTADOR_CERTIFICADO
    {
        public int PRCE_CD_ID { get; set; }
        public int PRES_CD_ID { get; set; }
        public int TICE_CD_ID { get; set; }
        public System.DateTime PRDE_DT_EMISSAO { get; set; }
        public System.DateTime PRCE_DT_VALIDADE { get; set; }
        public string PRCE_AQ_ARQUIVO { get; set; }
        public int PRCE_IN_ATIVO { get; set; }
    
        public virtual PRESTADOR PRESTADOR { get; set; }
        public virtual TIPO_CERTIFICADO TIPO_CERTIFICADO { get; set; }
    }
}
