//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTADOR_BANCO
    {
        public int PRBA_CD_ID { get; set; }
        public int PRES_CD_ID { get; set; }
        public int BANC_CD_ID { get; set; }
        public int TICO_CD_ID { get; set; }
        public string PRBA_NR_AGENCIA { get; set; }
        public string PRBA_NR_CONTA { get; set; }
        public int PRBA_IN_ATIVO { get; set; }
    
        public virtual BANCO BANCO { get; set; }
        public virtual PRESTADOR PRESTADOR { get; set; }
        public virtual TIPO_CONTA TIPO_CONTA { get; set; }
    }
}
