//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTADOR_REGIAO
    {
        public int PRRE_CD_ID { get; set; }
        public int PRES_CD_ID { get; set; }
        public int REGI_CD_ID { get; set; }
        public int RECO_CD_ID { get; set; }
        public decimal PRRE_VL_PRECO_BASE { get; set; }
        public Nullable<decimal> PRRE_VL_PRECO_MAXIMO { get; set; }
        public Nullable<decimal> PRRE_VL_PRECO_MINIMO { get; set; }
        public Nullable<decimal> PRRE_ACRESCIMO_HORA { get; set; }
        public Nullable<int> PRR_NR_DIAS_CARENCIA { get; set; }
        public int PRRE_IN_SEGUNDA { get; set; }
        public int PRRE_IN_TERCA { get; set; }
        public int PRRE_IN_QUARTA { get; set; }
        public int PRRE_IN_QUINTA { get; set; }
        public int PRRE_IN_SEXTA { get; set; }
        public int PRRE_IN_SABADO { get; set; }
        public Nullable<int> PRRE_IN_DOMINGO { get; set; }
        public Nullable<int> PRRE_IN_SLA { get; set; }
        public Nullable<int> PRRE_IN_PRIORIDADE { get; set; }
        public int PRRE_IN_ATIVO { get; set; }
    
        public virtual PRESTADOR PRESTADOR { get; set; }
        public virtual REGIAO_COBERTURA REGIAO_COBERTURA { get; set; }
        public virtual REGIAO REGIAO { get; set; }
    }
}
