//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTADOR_ENDERECO_VERIFICACAO
    {
        public int PEVE_CD_ID { get; set; }
        public int PREE_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public System.DateTime PEVE_DT_VERIFICACAO { get; set; }
        public string PEVE_NM_VERIFICACAO { get; set; }
        public string PEVE_TX_OBSERVACAO { get; set; }
        public int PEVE_IN_ATIVO { get; set; }
    
        public virtual PRESTADOR_ENDERECO_ESTOQUE PRESTADOR_ENDERECO_ESTOQUE { get; set; }
        public virtual USUARIO_SUGESTAO USUARIO_SUGESTAO { get; set; }
    }
}
