//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTADOR_VEICULO_FUNCAO
    {
        public int PRVF_CD_ID { get; set; }
        public int PRVE_CD_ID { get; set; }
        public int VEFU_CD_ID { get; set; }
        public int PRVF_IN_ATIVO { get; set; }
    
        public virtual PRESTADOR_VEICULO PRESTADOR_VEICULO { get; set; }
        public virtual VEICULO_FUNCAO VEICULO_FUNCAO { get; set; }
    }
}
