//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_PERGUNTAS_OPCAO
    {
        public int PRPO_CD_ID { get; set; }
        public int PRPE_CD_ID { get; set; }
        public string PRPO_NM_OPCAO { get; set; }
        public int PRPO_IN_ATIVO { get; set; }
    
        public virtual PRODUTO_PERGUNTAS PRODUTO_PERGUNTAS { get; set; }
    }
}
