//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUTO_COMPRA()
        {
            this.ITEM_PEDIDO_COMPRA = new HashSet<ITEM_PEDIDO_COMPRA>();
        }
    
        public int PROD_CD_ID { get; set; }
        public int CAPR_CD_ID { get; set; }
        public int SCPR_CD_ID { get; set; }
        public int UNID_CD_ID { get; set; }
        public string PROD_NM_NOME { get; set; }
        public string PROD_DS_DESCRICAO { get; set; }
        public string PROD_NM_FABRICANTE { get; set; }
        public string PROD_NM_MARCA { get; set; }
        public string PROD_NM_MODELO { get; set; }
        public string PROD_NR_REFERENCIA { get; set; }
        public string PROD_BC_BARCODE { get; set; }
        public string PROD_AQ_FOTO { get; set; }
        public int PROD_QN_QUANTIDADE_MINIMA { get; set; }
        public int PROD_QN_QUANTIDADE_MAXIMA { get; set; }
        public int PROD_QN_ESTOQUE { get; set; }
        public Nullable<decimal> PROD_VL_ULTIMO_CUSTO { get; set; }
        public Nullable<System.DateTime> PROD_DT_ULTIMA_MOVIMENTACAO { get; set; }
        public int PROD_IN_AVISA_MINIMO { get; set; }
        public int PROD_IN_ATIVO { get; set; }
        public int DEPARTAMENTODEPT_CD_ID { get; set; }
    
        public virtual CATEGORIA_PRODUTO CATEGORIA_PRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_PEDIDO_COMPRA> ITEM_PEDIDO_COMPRA { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
        public virtual SUBCATEGORIA_PRODUTO SUBCATEGORIA_PRODUTO { get; set; }
    }
}
