//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTOS_RESPOSTA
    {
        public int PRRE_CD_ID { get; set; }
        public int PRPE_CD_ID { get; set; }
        public int OSPD_CD_ID { get; set; }
        public string PRRE_NM_RESPOSTA { get; set; }
        public int PRRE_IN_ATIVO { get; set; }
    
        public virtual ORDEM_SERVICO_PRODUTO ORDEM_SERVICO_PRODUTO { get; set; }
        public virtual PRODUTO_PERGUNTAS PRODUTO_PERGUNTAS { get; set; }
    }
}
