//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPOSTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPOSTA()
        {
            this.ORDEM_SERVICO_PROPOSTA = new HashSet<ORDEM_SERVICO_PROPOSTA>();
        }
    
        public int PROP_CD_ID { get; set; }
        public string PROP_NM_NOME { get; set; }
        public System.DateTime PROP_DT_CRIACAO { get; set; }
        public System.DateTime PROP_DT_VALIDADE { get; set; }
        public int PROP_IN_ATIVO { get; set; }
        public string PROP_TX_TEXTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEM_SERVICO_PROPOSTA> ORDEM_SERVICO_PROPOSTA { get; set; }
    }
}
