//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGIAO_COBERTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REGIAO_COBERTURA()
        {
            this.PRESTADOR_REGIAO = new HashSet<PRESTADOR_REGIAO>();
        }
    
        public int RECO_CD_ID { get; set; }
        public int REGI_CD_ID { get; set; }
        public string RECO_NM_CIDADE { get; set; }
        public int UF_CD_ID { get; set; }
        public string RECO_NR_CEP_INICIO { get; set; }
        public string RECO_NR_CEP_FINAL { get; set; }
        public decimal RECO_VL_PRECO_BASE { get; set; }
        public decimal RECO_VL_PRECO_MAXIMO { get; set; }
        public decimal RECO_VL_PRECO_MINIMO { get; set; }
        public int RECO_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTADOR_REGIAO> PRESTADOR_REGIAO { get; set; }
        public virtual REGIAO REGIAO { get; set; }
        public virtual UF UF { get; set; }
    }
}
