//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_PRODUTO()
        {
            this.ORDEM_SERVICO_PRODUTO = new HashSet<ORDEM_SERVICO_PRODUTO>();
            this.PARCEIRO_PRECO = new HashSet<PARCEIRO_PRECO>();
            this.PRODUTO_PERGUNTAS = new HashSet<PRODUTO_PERGUNTAS>();
        }
    
        public int TIPR_CD_ID { get; set; }
        public int LIPR_CD_ID { get; set; }
        public string TIPR_NM_NOME { get; set; }
        public Nullable<int> TIPR_NR_PESO { get; set; }
        public string TIPR_DS_DESRICAO { get; set; }
        public int TIPR_IN_ATIVO { get; set; }
    
        public virtual LINHA_PRODUTO LINHA_PRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEM_SERVICO_PRODUTO> ORDEM_SERVICO_PRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARCEIRO_PRECO> PARCEIRO_PRECO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_PERGUNTAS> PRODUTO_PERGUNTAS { get; set; }
    }
}
