//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ITEM_PESQUISA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_ITEM_PESQUISA()
        {
            this.CLIENTE_PERGUNTA = new HashSet<CLIENTE_PERGUNTA>();
            this.PESQUISA_ITEM = new HashSet<PESQUISA_ITEM>();
            this.PRODUTO_PERGUNTAS = new HashSet<PRODUTO_PERGUNTAS>();
        }
    
        public int TIIT_CD_ID { get; set; }
        public string TIIT_NM_NOME { get; set; }
        public int TIIT_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_PERGUNTA> CLIENTE_PERGUNTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PESQUISA_ITEM> PESQUISA_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_PERGUNTAS> PRODUTO_PERGUNTAS { get; set; }
    }
}
