//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_CERTIFICADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_CERTIFICADO()
        {
            this.PRESTADOR_CERTIFICADO = new HashSet<PRESTADOR_CERTIFICADO>();
        }
    
        public int TICE_CD_ID { get; set; }
        public string TICE_NM_NOME { get; set; }
        public int TICE_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTADOR_CERTIFICADO> PRESTADOR_CERTIFICADO { get; set; }
    }
}
