//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEICULO_FUNCAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEICULO_FUNCAO()
        {
            this.PRESTADOR_VEICULO_FUNCAO = new HashSet<PRESTADOR_VEICULO_FUNCAO>();
        }
    
        public int VEFU_CD_ID { get; set; }
        public string VEFU_NM_NOME { get; set; }
        public int VEFU_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTADOR_VEICULO_FUNCAO> PRESTADOR_VEICULO_FUNCAO { get; set; }
    }
}
